version: '3'

services:
  app:
    build: .
    volumes:
      - '.:/usr/src/metricas'
    ports:
      - '4300:4300'
    command: >
      bash -c "npm run start"
    networks:
      - default
      - metricas

networks:
  default:
  metricas:
    external: true
